spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  sql:
    init:
      mode: never

server:
  servlet:
    session:
      cookie:
        secure: true

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
